alphagov/verify-stub-idp

smoke-test/run-smoke-test.sh

set -e was causing script to exit before docker-compose
down was executed. Add 'down' to trap to ensure containers
are always cleaned up

BAU: Clean up smoke test containers

---

build.gradle
src/main/java/uk/gov/ida/stub/idp/repositories/HardCodedTestUserList.java

There is a seperate commit in verify-acceptance-tests for make use of these.

EID-673: Add users with non-ASCII names for testing purposes.

---

build.gradle
src/integration-test/java/uk/gov/ida/apprule/EidasUserLogsInIntegrationTests.java
src/integration-test/java/uk/gov/ida/apprule/steps/AuthnRequestSteps.java
src/integration-test/java/uk/gov/ida/apprule/support/EidasAuthnRequestBuilder.java
src/main/java/uk/gov/ida/stub/idp/domain/EidasAuthnRequest.java
src/main/java/uk/gov/ida/stub/idp/domain/RequestedAttribute.java
src/main/java/uk/gov/ida/stub/idp/services/EidasAuthnResponseService.java
src/main/java/uk/gov/ida/stub/idp/views/EidasDebugPageView.java
src/test/java/uk/gov/ida/stub/idp/domain/EidasAuthnRequestTest.java

Fix up usage of the `RequestedAttribute`s now that they are actually being
unmarshalled...
Two possible issues:
* I'm not sure what `shouldConvertAuthnRequestToEidasAuthnRequest` is testing
* This might cause issues with serializing/de-serializing the eidas sessions in the db?

bau: update saml libs

---

bin/services.yaml

The `services.yaml` file defines the paths to subprojects used by
`bin/build.rb`. Update path since stub-idp has been moved to a subproject in this
repo.

BAU: Fix stub-idp path in services.yaml

---

inttest.gradle
stub-idp/build.gradle

- IntelliJ was complaining when importing the project into intellij, this is likely to be due to the recent project structure change. All repos now sit as children, therefore the first change to inttest.gradle is to ensure it looks in the right location. It also seemed to need the "idea" gradle plugin for the build.gradle in stub-idp.

Bau - Minor fix to allow import into intellij

---

build.gradle
stub-idp/src/integration-test/java/uk/gov/ida/apprule/support/SamlDecrypter.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java

- eIDAS assertions should only be signed using either RSASSA-PSS or ECDSA. This
change will ensure that eidas assertions are signed using RSASSA-PSS.
- However as our private keys are RSA, to sign with ECDSA would require a different private key.
Which would require a significant amount of work. We are aware that some proxy nodes use ECDSA,
which will allow us to test this in integration.
- The MSA will need to be [upgraded and released](https://github.com/alphagov/verify-matching-service-adapter/pull/91) before this is release so it can support the required algorithms.

EID-835 - Sign stub country assertions using RSASSA-PSS

---

build.gradle
stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/Urls.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/exceptions/InvalidSigningAlgorithmException.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/resources/eidas/EidasConsentResource.java
stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/eidasConsent.ftl
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasConsentResourceTest.java

- By default Stub Country's response is signed with rsasha256, however this
change will allow stub country to sign assertions with the rsassa-pss signing algorithm through
the acceptance tests. This is to ensure that the MSA can support responses with the rsassa-pss signing algorithm as per the eidas crypto spec. 
- The acceptance test will overwrite the value in eidasConsent.ftl with the rsassa-pss algorithm and perform a journey using stub-country. 
- Upgraded to latest version of ida_utils and saml_libs.

EID-894 - Give stub country the ability to support other signing algorithms

---

stub-idp/src/test/java/uk/gov/ida/stub/idp/services/ServiceListServiceTest.java

Small change to make test string match correct url in frontend rather
than hub to save potential confusion.
solo: @rachelthecodesmith

HUB-271: Changed url string in test to reflect correct endpoint

---

stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/singleIdpPromptPage.ftl

Renaming test-rp name "register for an identity" profile to "test GOV.UK Verify user journeys"
to make the content more readable.

 FIREBREAK: Rename test-rp

---

bin/build.rb

The orchestration ready script depends on this library.

BAU: Add python-httplib2 dependency to Debian packages

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/services/ServiceListService.java
stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/singleIdpPromptPage.ftl

In order for us to test the single IDP journey in staging and integration
we need to initiate the single IDP journey manually (via form). This is
due to the fact that Stub IDP is not able to talk to Frontend in these
environments.
- changed the exception type when the NETWORK_ERROR occurs, the app doesn't crash
- added a POST form to the prompt page for the tests to use

HUB-296: Add acceptance tests for Single IDP journey

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/jdbc/migrations/DatabaseMigrationRunner.java

Currently Encoded password contains the letters "h2" which is causing database migration to pick up wrong versions of the script.
This is a quick fix. Long term fix required.

BAU: Fix Database Migration Runner H2/Postgres switch

---

stub-idp/src/integration-test/java/uk/gov/ida/apprule/UserLogsInIntegrationTests.java
stub-idp/src/integration-test/java/uk/gov/ida/apprule/support/StubIdpAppRule.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/configuration/StubIdpConfiguration.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/SessionRepository.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/SessionRepositoryBase.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/reaper/ManagedStaleSessionReaper.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/reaper/StaleSessionReaper.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/reaper/StaleSessionReaperConfiguration.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/repositories/jdbc/JDBIIdpSessionRepositoryTest.java

Will close this in a week or so if it's not got any take up.  I'm not really sure how to test this.  I've run it locally by changing the config to 1s and checking the logs - see the ignored test.
interesting to note that it's not possible to separately count verify
vs eidas sessions
Closes #37

add a stale session reaper to remove stale sessions from the db

---

deploy_to_paas.sh

Default healthcheck timeout is set to 60 seconds, however in integration we have a
large number of IDPs in the config which takes more than 60 seconds to load.
Therefore the app is declared unhealthy before it finishing updating all the IDPs.

BAU: Extend cf timeout

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/views/DebugPageView.java
stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/debugPage.ftl
stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/idpPage.ftl

Add robot-repellent meta tag to idpPageTemplate.ftl.
Restrict output of debug page to values that exist in the session.

BAU disable robots and fix bug in debug page

---

.travis.yml

- Stub-idp builds successfully on jdk10 and jdk11 so no need to allow failures.

bau - Dont allow failures on travis

---

build.gradle
stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpApplication.java

Update DropWizard to latest release.
Change .getSuffix() to .getConfigureationKey() on FreemarkerViewRenderer used when configuring the ViewBundle.

HUB-51_update_dropwizard_to_1.3.8

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/HardCodedTestUserList.java

Needed to pass validation expected of normal IDPs.

BAU: Add from and to values to test user attributes

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/HardCodedTestUserList.java

- If you only have one e.g. FirstName, you expect it to be current (i.e.
it has no "To" date)
- The MSA only adds current attributes to the assertions when doing user
account creation so when setting a "To" date, none of those attributes
are included
Co-authored-by: Christopher Wynne <christopher.wynne@digital.cabinet-office.gov.uk>

BAU: Don't set To dates for default users

---

inttest.gradle
stub-idp/src/integration-test/java/uk/gov/ida/apprule/EidasUserLogsInIntegrationTests.java
stub-idp/src/integration-test/java/uk/gov/ida/apprule/PreRegistrationIntegrationTest.java

Integration tests were accidentally disabled by #29. Re-enable them. Temporarily ignore the failing tests to allow the rest to be turned on in CI.
It's very sad that gradle allows this to happen 😞 
See https://govuk.zendesk.com/agent/tickets/3637272

ZD3637272: re-enable integration tests

---

manifest.yml

PaaS are removing the stack cflinuxfs2 and require all apps to be
upgraded to cflinuxfs3.

BAU: Upgrade PaaS stack to cflinuxfs3

---

.travis.yml
build.gradle
stub-idp/src/integration-test/java/uk/gov/ida/apprule/HomePageIntegrationTest.java
stub-idp/src/integration-test/java/uk/gov/ida/apprule/support/SamlDecrypter.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/StubIdpModuleTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/builders/CountryMetadataBuilderTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/cookies/CookieFactoryTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/cookies/HmacValidatorTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/filters/SecurityHeadersFilterTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/filters/SessionCookieValueMustExistAsASessionFilterTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/ConsentResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/DebugPageResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasConsentResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasLoginPageResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasProxyNodeServiceMetadataResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasRegistrationPageResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/LoginPageResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/RegistrationPageResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/SingleIdpPromptResourceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/services/EidasAuthnResponseServiceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/services/IdpUserServiceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/services/NonSuccessAuthnResponseServiceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/services/ServiceListServiceTest.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/services/StubCountryServiceTest.java

This is to enable deploying stub IDP from Concourse

BAU: Update libs and build Stub IDP on Java 11

---

stub-idp-saml-test/build.gradle
stub-idp-saml/build.gradle

- stub-idp-saml and stub-idp-saml-test libs to be built and uploaded to Artifactory in the build-libraries Concourse pipeline.
- This change provides the config to access Artifactory.

BAU Upload libs to Artifactory in Concourse pipleline

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/domain/EidasScheme.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/domain/factories/StubCoreTransformersFactory.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/domain/factories/StubTransformersFactory.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/saml/transformers/EidasResponseTransformerProvider.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/services/EidasAuthnResponseService.java
stub-idp/src/main/java/uk/gov/ida/stub/idp/transformers/UnsignedAssertionCapableResponseToSignedStringTransformer.java
stub-idp/src/test/java/uk/gov/ida/stub/idp/services/EidasAuthnResponseServiceTest.java

This pull request is part of a group of 5, made across the following verify repositories, containing adjustments to enable **stub-idp** to support an additional country: `stub-country-unsigned-assertions`.
As the name suggests, `stub-country-unsigned-assertions` generates SAML messages with unsigned assertions.
* **verify-stub-idp**
* Allow stub-idp supported stub countries to differentiate their behaviour by `EidasScheme`.
* Create `UnsignedAssertionCapableResponseToSignedStringTransformer` and use it in place of `ResponseToSignedStringTransformer` when generating stub-country-unsigned-assertion responses.
* **verify-frontend**
* Add stub-country-unsigned-assertions to the stub_api.
* Add country flag (xx).
* **verify-frontend-federation-config**
* Add scheme, locale, flag, and logo for …

EID-1677 send unsigned assertions from stub-country

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/services/IdpUserService.java

DEFRA Rural Payments Agency couldn't test the Verify matching process because Stub IDP wasn't returning the town as part of the address.  This change adds the town so that matching works properly and DEFRA can more easily test in the integration environment.

ZD-3747417 Fix Stub-IDP address fields

---

stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/eidasLoginPage.ftl

This change modifies the id of the sign assertions checkbox to make it meaningful in the context of the name/id/value triplet for HTML checkboxes.
Essential for: https://github.com/alphagov/verify-acceptance-tests/pull/73

EID-1611 improve the uniqueness of the id for the sign assertions checkbox

---

stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java

A tiny artefact remains from the heady days of unsigned assertions country. This PR removes an unused parameter.

EID-1848 remove remaining unsigned assertions country artefacts

---

configuration/local/stub-idp.yml
startup.sh

This change updates startup.sh script and adds a local stub-idp.yml file so that the script can build and start stub-idp application without any errors.
Author: @adityapahuja

BAU: Fix startup issue

---

manifest.yml.tmpl

This change renames Logit's service name from stub-idp-logit-<environment> to logit-<environment> since Logit service is not just for stub-idp application. It is for all applications running in the environment.
Author: @adityapahuja

AUT-14: Rename logit's service name

---

stub-idp-saml-test/build.gradle
stub-idp-saml/build.gradle
stub-idp/build.gradle

Bintray is the source of truth now, for stub-idp-saml and
stub-idp-saml-test.
Bintray is made available via whitelisted-repos on artifactory, so we
still pull dependencies down using artifactory, but we only need to
push dependencies to bintray.
The exception is stub-idp itself; our artifact store for this is S3;
concourse builds stub-idp and uploads the artifacts to an S3 bucket,
and deploys from there to PaaS.

Stop publishing to artifactory

---

manifest.yml.tmpl

This change updates healthcheck timeout from 60s to 120s to resolve the following error.
`ERR Timed out after 1m0s: health check never passed.`
Author: @adityapahuja

BAU: Increase healthcheck timeout to 120s

---

configuration/local/stub-idp.yml
startup.sh

Postgres Docker now requires a password to startup. I don't know how
long this has been a requirement but it has caused me some issues on
Linux and I think I have seen the issue on my mac as well. This commit
fixes that issue.

Give PostgreSQL docker a password

---

Dockerfile

This updates the Dockerfile for stub-idp to use Java 11.

HUB-720 Update Stub-idp docker to Java 11

---

Dockerfile
build.gradle
stub-idp/src/integration-test/java/uk/gov/ida/apprule/support/SamlDecrypter.java

Update dockerfile to use version 6.8 of gradle - the vendored version
has shifted to v7 which doesn't work.
Remove the versions plugin, and the buildscript block which was only
there to bring it in.
Bump versions of dependencies to ensure they're being pulled from maven
central.
Update public builds to use maven central and remove redundant repos.
Update `SamlDecrypter` to work with the new versions of hub-saml.

HUB-915: Pull from maven central

---

Dockerfile

When building the dockerfile from verify-local-startup the stub-idp repository doesn't build due to it missing `publish.gradle`. The following is the log taken from verify-local-startup when trying to build this repo:
```
#18 [build 10/14] RUN gradle :stub-idp:install
#18 sha256:95f50bf7d2616ae9f0c6e1eb8555f23c6e36bf3ec29dfd6d8c9a7bd874492267
#18 1.416
#18 1.416 Welcome to Gradle 6.8.3!
#18 1.416
#18 1.416 Here are the highlights of this release:
#18 1.416  - Faster Kotlin DSL script compilation
#18 1.416  - Vendor selection for Java toolchains
#18 1.417  - Convenient execution of tasks in composite builds
#18 1.417  - Consistent dependency resolution
#18 1.417
#18 1.417 For more details see https://docs.gradle.org/6.8.3/release-notes.html
#18 1.417
#18 1.781 Starting a Gradle Daemon …
```

Dockerfile missing publish.gradle causing verify-local-startup to fail

---

Dockerfile
ci/build.yml
smoke-test/Dockerfile

We've moved back to using Docker Hub rather than GitHub container registry so un-doing the work that was done 5 months ago. Moved back to versions previously set https://github.com/alphagov/verify-stub-idp/commit/d6266362fbec609dc31f351cefbde01168fce1f0 but might need updating later.

[HUB-841] Use dockerhub rather than ghcr

---

ci/build.yml

A change was made a while ago so that version used by distZip for naming
was set to the value of `build_version` in the root gradle file.
`build_version` is composed from the open saml version set as well as
the env variable `BUILD_NUMBER`. If `BUILD_NUMBER` is not set then
`SNAPSHOT` is used instead.
This pipeline hasn't been updated to reflect this and so all new
artifacts have the same name - `stub-idp-3.4.3-SNAPSHOT.zip`
This all means that the pipeline doesn't register a new build artifact
as a new version and so it doesn't get released.
Providing the Concourse version number as BUILD_NUMBER ensures each new
build has a unique artifact name and triggers the pipeline correctly.

BAU: Fix distZip artifact name in pipeline
