alphagov/verify-stub-idp

- src/main/resources/uk/gov/ida/stub/idp/views/loginPage.ftl
> bau: use correct descriptions

- manifest.yml
This environment variable is now set through Jenkins.
> Remove EUROPEAN_IDENTITY_ENABLED from manifest

- src/main/java/uk/gov/ida/stub/idp/auth/UserResourceBasicAuthFilter.java
> bau: add logging for basic auth access

- build.gradle
- src/main/java/uk/gov/ida/stub/idp/domain/factories/MatchingDatasetFactory.java
Libraries bumped: stub-idp-saml, ida-utils, ida-dev-pki, saml-libs, ida-test-utils, hub-saml
> BAU: Update libraries to the latest versions

- src/main/java/uk/gov/ida/stub/idp/resources/ConsentResource.java
> bau: send a real ip address back to the hub

- src/integration-test/java/uk/gov/ida/apprule/EidasUserLogsInIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/UserLogsInIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/steps/AuthnRequestSteps.java
- src/main/java/uk/gov/ida/stub/idp/StubIdpApplication.java
- src/main/java/uk/gov/ida/stub/idp/Urls.java
- src/main/java/uk/gov/ida/stub/idp/resources/eidas/EidasDebugPageResource.java
- src/main/java/uk/gov/ida/stub/idp/views/EidasDebugPageView.java
- src/main/resources/uk/gov/ida/stub/idp/views/eidasDebugPage.ftl
- src/main/resources/uk/gov/ida/stub/idp/views/eidasLoginPage.ftl
- src/main/resources/uk/gov/ida/stub/idp/views/eidasRegistrationPage.ftl
For some reason the requested attributes are not in the session from
the test authnrequest that is built
Pair: WillPa
> bau: add an eidas debug page

- .gitignore
- .travis.yml
- README.md
- build.gradle
Changes copied from MSA
Pair: WillPa
> bau: build on travis

- .travis.yml
> bau: all the javas

- src/integration-test/java/uk/gov/ida/apprule/AutoEscapingIntegrationTest.java
- src/integration-test/java/uk/gov/ida/apprule/EidasCountryMetadataIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/EidasUserLogsInIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/EmojiSupportIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/HintsIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/LevelOfAssuranceIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/UserLogsInIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/UserRepositoryIntegrationTests.java
- src/integration-test/java/uk/gov/ida/apprule/support/IntegrationTestHelper.java
- src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java
> bau: make repositories singletons

- src/main/java/uk/gov/ida/stub/idp/exceptions/mappers/CatchAllExceptionMapper.java
- src/main/java/uk/gov/ida/stub/idp/exceptions/mappers/IdpNotFoundExceptionMapper.java
- src/main/java/uk/gov/ida/stub/idp/exceptions/mappers/SessionSerializationExceptionMapper.java
> bau: log errors

- src/main/java/uk/gov/ida/stub/idp/repositories/HardCodedTestUserList.java
> bau: add one test user from the example local matching service

- .dockerignore
- Dockerfile
- Stub IDP has done some shuffling so Docker needs to do
a little shuffling too
> BAU: Fix docker build

- configuration/stub-idp.yml
- stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpModule.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/configuration/SingleIdpConfiguration.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/configuration/StubIdpConfiguration.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/domain/Service.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/exceptions/FeatureNotEnabledException.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/services/ServiceListService.java
- stub-idp/src/test/java/uk/gov/ida/stub/idp/services/ServiceListServiceTest.java
Add New Service to read list of services from Hub that can be injected into controllers.
> HUB-218: Read List of Services From Hub

- stub-idp/build.gradle
The from was referencing undefined variable.
> BAU: Fixed copying the logos

- jenkins.sh
Specify the copy task explicitly
> BAU: fix for missing logos

- stub-idp/src/integration-test/java/uk/gov/ida/apprule/SecurityHeadersIntegrationTests.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/StubIdpApplication.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/filters/SecurityHeadersFilter.java
- stub-idp/src/main/resources/assets/scripts/dob-validator.js
- stub-idp/src/main/resources/assets/scripts/gender-picker-toggle.js
- stub-idp/src/main/resources/assets/scripts/saml-redirect-auto-submit.js
- stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/eidasRegistrationPage.ftl
- stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/registrationPage.ftl
- stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/samlRedirectView.ftl
- stub-idp/src/test/java/uk/gov/ida/stub/idp/filters/SecurityHeadersFilterTest.java
This has been tested locally.  Will close this in a week or so if there's no interest :)
> Add a content-security-policy

- stub-idp/src/integration-test/java/uk/gov/ida/apprule/PreRegistrationIntegrationTest.java
- stub-idp/src/integration-test/java/uk/gov/ida/apprule/steps/Cookies.java
- stub-idp/src/integration-test/java/uk/gov/ida/apprule/steps/PreRegistrationSteps.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/Urls.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/resources/idp/RegistrationPageResource.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/resources/idp/SingleIdpPromptPageResource.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/views/SamlMessageRedirectViewFactory.java
- stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/SingleIdpPromptResourceTest.java
Fixed issue with non-existent sessions. Delete session cookie. Add query parameter to control when user details are displayed.
> hub-221 stub idp pre-registration

- stub-idp-saml-test/build.gradle
- stub-idp-saml/build.gradle
Upgrade Bintray plugin to 1.8.4.
https://github.com/bintray/gradle-bintray-plugin/issues/234
> BAU: Bintray error during build on Gradle > 4.8

- README.md
This is not knit-picking - I want to check the new job I created in this other PR is triggered by a PR merge https://github.com/alphagov/verify-jenkins-job-builder/pull/314
> Minor formatting change

- build.gradle
Various updates since Aug 2018.
See here for changes: https://build.ida.digital.cabinet-office.gov.uk/job/ida-utils/
> BAU Bump utils to 350

- stub-idp-saml/src/test/java/uk/gov/ida/saml/idp/builders/IdentityProviderAuthnStatementBuilder.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/resources/UserResource.java
Address points raised during https://github.com/alphagov/verify-stub-idp/pull/86
> Cleanups round 2

- stub-idp/src/integration-test/java/uk/gov/ida/apprule/support/eidas/EidasProfileValidationSpecification.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/domain/SamlResponse.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/exceptions/InvalidSecureCookieException.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/filters/SessionCookieValueMustExistAsASessionFilter.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/repositories/IdpSession.java
- stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasProxyNodeServiceMetadataResourceTest.java
We can make better use of `java.util.Optional` than we do.
Simplify some code a bit
Also, make `EidasProfileValidationSpecification` package-private
> Better utilise Optional

- stub-idp/src/main/java/uk/gov/ida/stub/idp/views/helpers/IdpUserHelper.java
There's a lot of control flow in this class centred around the absence or
otherwise of values. The Streams API lets us encapsulate this logic much more
neatly.
> Simplify IdpUserHelper using Streams

- build.gradle
This is to fix the Travis build
> BAU: Add public maven repo to project dependencies

- build.gradle
- Bringing lib versions into line so that Compliance Tool will build
> BAU: Version Bump for Compliance Tool

- README.md
Clarify instructions for how to find users; update the URI for the onboarding docs.
> Clarify instructions for stub IDPs

- stub-idp/src/main/java/uk/gov/ida/stub/idp/resources/eidas/EidasRegistrationPageResource.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/services/StubCountryService.java
- stub-idp/src/main/java/uk/gov/ida/stub/idp/views/EidasRegistrationPageView.java
- stub-idp/src/main/resources/uk/gov/ida/stub/idp/views/eidasRegistrationPage.ftl
- stub-idp/src/test/java/uk/gov/ida/stub/idp/resources/EidasRegistrationPageResourceTest.java
This PR adds a 'sign assertions' checkbox to the Registration form.
> EID-1611 Add the signed assertions checkbox to the registration form

- build.gradle
- publish.gradle
- stub-idp-saml-test/build.gradle
- stub-idp-saml/build.gradle
- stub-idp/build.gradle
- stub-idp/src/main/java/uk/gov/ida/stub/idp/listeners/StubIdpsFileListener.java
This PR adds missing javadocs and sources.jar
Included missing javadocs and sources .jar
> HUB-866: Republish to maven central
